// Kompletný zoznam krajín a ich telefónnych predvolieb (international dialing codes).
export interface DialCode { iso: string; dial: string; sk: string; en: string }

export const DIAL_CODES: DialCode[] = [
  { iso: "SK", dial: "+421", sk: "Slovensko", en: "Slovakia" },
  { iso: "CZ", dial: "+420", sk: "Česko", en: "Czechia" },
  { iso: "AT", dial: "+43", sk: "Rakúsko", en: "Austria" },
  { iso: "HU", dial: "+36", sk: "Maďarsko", en: "Hungary" },
  { iso: "PL", dial: "+48", sk: "Poľsko", en: "Poland" },
  { iso: "DE", dial: "+49", sk: "Nemecko", en: "Germany" },
  { iso: "GB", dial: "+44", sk: "Spojené kráľovstvo", en: "United Kingdom" },
  { iso: "US", dial: "+1", sk: "USA", en: "United States" },
  { iso: "AF", dial: "+93", sk: "Afganistan", en: "Afghanistan" },
  { iso: "AL", dial: "+355", sk: "Albánsko", en: "Albania" },
  { iso: "DZ", dial: "+213", sk: "Alžírsko", en: "Algeria" },
  { iso: "AD", dial: "+376", sk: "Andorra", en: "Andorra" },
  { iso: "AO", dial: "+244", sk: "Angola", en: "Angola" },
  { iso: "AG", dial: "+1268", sk: "Antigua a Barbuda", en: "Antigua and Barbuda" },
  { iso: "AR", dial: "+54", sk: "Argentína", en: "Argentina" },
  { iso: "AM", dial: "+374", sk: "Arménsko", en: "Armenia" },
  { iso: "AU", dial: "+61", sk: "Austrália", en: "Australia" },
  { iso: "AZ", dial: "+994", sk: "Azerbajdžan", en: "Azerbaijan" },
  { iso: "BS", dial: "+1242", sk: "Bahamy", en: "Bahamas" },
  { iso: "BH", dial: "+973", sk: "Bahrajn", en: "Bahrain" },
  { iso: "BD", dial: "+880", sk: "Bangladéš", en: "Bangladesh" },
  { iso: "BB", dial: "+1246", sk: "Barbados", en: "Barbados" },
  { iso: "BY", dial: "+375", sk: "Bielorusko", en: "Belarus" },
  { iso: "BE", dial: "+32", sk: "Belgicko", en: "Belgium" },
  { iso: "BZ", dial: "+501", sk: "Belize", en: "Belize" },
  { iso: "BJ", dial: "+229", sk: "Benin", en: "Benin" },
  { iso: "BT", dial: "+975", sk: "Bhután", en: "Bhutan" },
  { iso: "BO", dial: "+591", sk: "Bolívia", en: "Bolivia" },
  { iso: "BA", dial: "+387", sk: "Bosna a Hercegovina", en: "Bosnia and Herzegovina" },
  { iso: "BW", dial: "+267", sk: "Botswana", en: "Botswana" },
  { iso: "BR", dial: "+55", sk: "Brazília", en: "Brazil" },
  { iso: "BN", dial: "+673", sk: "Brunej", en: "Brunei" },
  { iso: "BG", dial: "+359", sk: "Bulharsko", en: "Bulgaria" },
  { iso: "BF", dial: "+226", sk: "Burkina Faso", en: "Burkina Faso" },
  { iso: "BI", dial: "+257", sk: "Burundi", en: "Burundi" },
  { iso: "KH", dial: "+855", sk: "Kambodža", en: "Cambodia" },
  { iso: "CM", dial: "+237", sk: "Kamerun", en: "Cameroon" },
  { iso: "CA", dial: "+1", sk: "Kanada", en: "Canada" },
  { iso: "CV", dial: "+238", sk: "Kapverdy", en: "Cape Verde" },
  { iso: "CF", dial: "+236", sk: "Stredoafrická rep.", en: "Central African Republic" },
  { iso: "TD", dial: "+235", sk: "Čad", en: "Chad" },
  { iso: "CL", dial: "+56", sk: "Čile", en: "Chile" },
  { iso: "CN", dial: "+86", sk: "Čína", en: "China" },
  { iso: "CO", dial: "+57", sk: "Kolumbia", en: "Colombia" },
  { iso: "KM", dial: "+269", sk: "Komory", en: "Comoros" },
  { iso: "CG", dial: "+242", sk: "Kongo", en: "Congo" },
  { iso: "CD", dial: "+243", sk: "Konžská dem. rep.", en: "Congo (DRC)" },
  { iso: "CR", dial: "+506", sk: "Kostarika", en: "Costa Rica" },
  { iso: "CI", dial: "+225", sk: "Pobrežie Slonoviny", en: "Côte d'Ivoire" },
  { iso: "HR", dial: "+385", sk: "Chorvátsko", en: "Croatia" },
  { iso: "CU", dial: "+53", sk: "Kuba", en: "Cuba" },
  { iso: "CY", dial: "+357", sk: "Cyprus", en: "Cyprus" },
  { iso: "DK", dial: "+45", sk: "Dánsko", en: "Denmark" },
  { iso: "DJ", dial: "+253", sk: "Džibutsko", en: "Djibouti" },
  { iso: "DM", dial: "+1767", sk: "Dominika", en: "Dominica" },
  { iso: "DO", dial: "+1809", sk: "Dominikánska rep.", en: "Dominican Republic" },
  { iso: "EC", dial: "+593", sk: "Ekvádor", en: "Ecuador" },
  { iso: "EG", dial: "+20", sk: "Egypt", en: "Egypt" },
  { iso: "SV", dial: "+503", sk: "Salvádor", en: "El Salvador" },
  { iso: "GQ", dial: "+240", sk: "Rovníková Guinea", en: "Equatorial Guinea" },
  { iso: "ER", dial: "+291", sk: "Eritrea", en: "Eritrea" },
  { iso: "EE", dial: "+372", sk: "Estónsko", en: "Estonia" },
  { iso: "SZ", dial: "+268", sk: "Eswatini", en: "Eswatini" },
  { iso: "ET", dial: "+251", sk: "Etiópia", en: "Ethiopia" },
  { iso: "FJ", dial: "+679", sk: "Fidži", en: "Fiji" },
  { iso: "FI", dial: "+358", sk: "Fínsko", en: "Finland" },
  { iso: "FR", dial: "+33", sk: "Francúzsko", en: "France" },
  { iso: "GA", dial: "+241", sk: "Gabon", en: "Gabon" },
  { iso: "GM", dial: "+220", sk: "Gambia", en: "Gambia" },
  { iso: "GE", dial: "+995", sk: "Gruzínsko", en: "Georgia" },
  { iso: "GH", dial: "+233", sk: "Ghana", en: "Ghana" },
  { iso: "GR", dial: "+30", sk: "Grécko", en: "Greece" },
  { iso: "GD", dial: "+1473", sk: "Grenada", en: "Grenada" },
  { iso: "GT", dial: "+502", sk: "Guatemala", en: "Guatemala" },
  { iso: "GN", dial: "+224", sk: "Guinea", en: "Guinea" },
  { iso: "GW", dial: "+245", sk: "Guinea-Bissau", en: "Guinea-Bissau" },
  { iso: "GY", dial: "+592", sk: "Guyana", en: "Guyana" },
  { iso: "HT", dial: "+509", sk: "Haiti", en: "Haiti" },
  { iso: "HN", dial: "+504", sk: "Honduras", en: "Honduras" },
  { iso: "HK", dial: "+852", sk: "Hongkong", en: "Hong Kong" },
  { iso: "IS", dial: "+354", sk: "Island", en: "Iceland" },
  { iso: "IN", dial: "+91", sk: "India", en: "India" },
  { iso: "ID", dial: "+62", sk: "Indonézia", en: "Indonesia" },
  { iso: "IR", dial: "+98", sk: "Irán", en: "Iran" },
  { iso: "IQ", dial: "+964", sk: "Irak", en: "Iraq" },
  { iso: "IE", dial: "+353", sk: "Írsko", en: "Ireland" },
  { iso: "IL", dial: "+972", sk: "Izrael", en: "Israel" },
  { iso: "IT", dial: "+39", sk: "Taliansko", en: "Italy" },
  { iso: "JM", dial: "+1876", sk: "Jamajka", en: "Jamaica" },
  { iso: "JP", dial: "+81", sk: "Japonsko", en: "Japan" },
  { iso: "JO", dial: "+962", sk: "Jordánsko", en: "Jordan" },
  { iso: "KZ", dial: "+7", sk: "Kazachstan", en: "Kazakhstan" },
  { iso: "KE", dial: "+254", sk: "Keňa", en: "Kenya" },
  { iso: "KI", dial: "+686", sk: "Kiribati", en: "Kiribati" },
  { iso: "KW", dial: "+965", sk: "Kuvajt", en: "Kuwait" },
  { iso: "KG", dial: "+996", sk: "Kirgizsko", en: "Kyrgyzstan" },
  { iso: "LA", dial: "+856", sk: "Laos", en: "Laos" },
  { iso: "LV", dial: "+371", sk: "Lotyšsko", en: "Latvia" },
  { iso: "LB", dial: "+961", sk: "Libanon", en: "Lebanon" },
  { iso: "LS", dial: "+266", sk: "Lesotho", en: "Lesotho" },
  { iso: "LR", dial: "+231", sk: "Libéria", en: "Liberia" },
  { iso: "LY", dial: "+218", sk: "Líbya", en: "Libya" },
  { iso: "LI", dial: "+423", sk: "Lichtenštajnsko", en: "Liechtenstein" },
  { iso: "LT", dial: "+370", sk: "Litva", en: "Lithuania" },
  { iso: "LU", dial: "+352", sk: "Luxembursko", en: "Luxembourg" },
  { iso: "MO", dial: "+853", sk: "Macao", en: "Macau" },
  { iso: "MG", dial: "+261", sk: "Madagaskar", en: "Madagascar" },
  { iso: "MW", dial: "+265", sk: "Malawi", en: "Malawi" },
  { iso: "MY", dial: "+60", sk: "Malajzia", en: "Malaysia" },
  { iso: "MV", dial: "+960", sk: "Maldivy", en: "Maldives" },
  { iso: "ML", dial: "+223", sk: "Mali", en: "Mali" },
  { iso: "MT", dial: "+356", sk: "Malta", en: "Malta" },
  { iso: "MH", dial: "+692", sk: "Marshallove ostrovy", en: "Marshall Islands" },
  { iso: "MR", dial: "+222", sk: "Mauritánia", en: "Mauritania" },
  { iso: "MU", dial: "+230", sk: "Maurícius", en: "Mauritius" },
  { iso: "MX", dial: "+52", sk: "Mexiko", en: "Mexico" },
  { iso: "FM", dial: "+691", sk: "Mikronézia", en: "Micronesia" },
  { iso: "MD", dial: "+373", sk: "Moldavsko", en: "Moldova" },
  { iso: "MC", dial: "+377", sk: "Monako", en: "Monaco" },
  { iso: "MN", dial: "+976", sk: "Mongolsko", en: "Mongolia" },
  { iso: "ME", dial: "+382", sk: "Čierna Hora", en: "Montenegro" },
  { iso: "MA", dial: "+212", sk: "Maroko", en: "Morocco" },
  { iso: "MZ", dial: "+258", sk: "Mozambik", en: "Mozambique" },
  { iso: "MM", dial: "+95", sk: "Mjanmarsko", en: "Myanmar" },
  { iso: "NA", dial: "+264", sk: "Namíbia", en: "Namibia" },
  { iso: "NR", dial: "+674", sk: "Nauru", en: "Nauru" },
  { iso: "NP", dial: "+977", sk: "Nepál", en: "Nepal" },
  { iso: "NL", dial: "+31", sk: "Holandsko", en: "Netherlands" },
  { iso: "NZ", dial: "+64", sk: "Nový Zéland", en: "New Zealand" },
  { iso: "NI", dial: "+505", sk: "Nikaragua", en: "Nicaragua" },
  { iso: "NE", dial: "+227", sk: "Niger", en: "Niger" },
  { iso: "NG", dial: "+234", sk: "Nigéria", en: "Nigeria" },
  { iso: "KP", dial: "+850", sk: "Severná Kórea", en: "North Korea" },
  { iso: "MK", dial: "+389", sk: "Severné Macedónsko", en: "North Macedonia" },
  { iso: "NO", dial: "+47", sk: "Nórsko", en: "Norway" },
  { iso: "OM", dial: "+968", sk: "Omán", en: "Oman" },
  { iso: "PK", dial: "+92", sk: "Pakistan", en: "Pakistan" },
  { iso: "PW", dial: "+680", sk: "Palau", en: "Palau" },
  { iso: "PS", dial: "+970", sk: "Palestína", en: "Palestine" },
  { iso: "PA", dial: "+507", sk: "Panama", en: "Panama" },
  { iso: "PG", dial: "+675", sk: "Papua-Nová Guinea", en: "Papua New Guinea" },
  { iso: "PY", dial: "+595", sk: "Paraguaj", en: "Paraguay" },
  { iso: "PE", dial: "+51", sk: "Peru", en: "Peru" },
  { iso: "PH", dial: "+63", sk: "Filipíny", en: "Philippines" },
  { iso: "PT", dial: "+351", sk: "Portugalsko", en: "Portugal" },
  { iso: "QA", dial: "+974", sk: "Katar", en: "Qatar" },
  { iso: "RO", dial: "+40", sk: "Rumunsko", en: "Romania" },
  { iso: "RU", dial: "+7", sk: "Rusko", en: "Russia" },
  { iso: "RW", dial: "+250", sk: "Rwanda", en: "Rwanda" },
  { iso: "KN", dial: "+1869", sk: "Svätý Krištof a Nevis", en: "Saint Kitts and Nevis" },
  { iso: "LC", dial: "+1758", sk: "Svätá Lucia", en: "Saint Lucia" },
  { iso: "VC", dial: "+1784", sk: "Svätý Vincent", en: "Saint Vincent" },
  { iso: "WS", dial: "+685", sk: "Samoa", en: "Samoa" },
  { iso: "SM", dial: "+378", sk: "San Maríno", en: "San Marino" },
  { iso: "ST", dial: "+239", sk: "Svätý Tomáš", en: "São Tomé and Príncipe" },
  { iso: "SA", dial: "+966", sk: "Saudská Arábia", en: "Saudi Arabia" },
  { iso: "SN", dial: "+221", sk: "Senegal", en: "Senegal" },
  { iso: "RS", dial: "+381", sk: "Srbsko", en: "Serbia" },
  { iso: "SC", dial: "+248", sk: "Seychely", en: "Seychelles" },
  { iso: "SL", dial: "+232", sk: "Sierra Leone", en: "Sierra Leone" },
  { iso: "SG", dial: "+65", sk: "Singapur", en: "Singapore" },
  { iso: "SI", dial: "+386", sk: "Slovinsko", en: "Slovenia" },
  { iso: "SB", dial: "+677", sk: "Šalamúnove ostrovy", en: "Solomon Islands" },
  { iso: "SO", dial: "+252", sk: "Somálsko", en: "Somalia" },
  { iso: "ZA", dial: "+27", sk: "Južná Afrika", en: "South Africa" },
  { iso: "KR", dial: "+82", sk: "Južná Kórea", en: "South Korea" },
  { iso: "SS", dial: "+211", sk: "Južný Sudán", en: "South Sudan" },
  { iso: "ES", dial: "+34", sk: "Španielsko", en: "Spain" },
  { iso: "LK", dial: "+94", sk: "Srí Lanka", en: "Sri Lanka" },
  { iso: "SD", dial: "+249", sk: "Sudán", en: "Sudan" },
  { iso: "SR", dial: "+597", sk: "Surinam", en: "Suriname" },
  { iso: "SE", dial: "+46", sk: "Švédsko", en: "Sweden" },
  { iso: "CH", dial: "+41", sk: "Švajčiarsko", en: "Switzerland" },
  { iso: "SY", dial: "+963", sk: "Sýria", en: "Syria" },
  { iso: "TW", dial: "+886", sk: "Taiwan", en: "Taiwan" },
  { iso: "TJ", dial: "+992", sk: "Tadžikistan", en: "Tajikistan" },
  { iso: "TZ", dial: "+255", sk: "Tanzánia", en: "Tanzania" },
  { iso: "TH", dial: "+66", sk: "Thajsko", en: "Thailand" },
  { iso: "TL", dial: "+670", sk: "Východný Timor", en: "Timor-Leste" },
  { iso: "TG", dial: "+228", sk: "Togo", en: "Togo" },
  { iso: "TO", dial: "+676", sk: "Tonga", en: "Tonga" },
  { iso: "TT", dial: "+1868", sk: "Trinidad a Tobago", en: "Trinidad and Tobago" },
  { iso: "TN", dial: "+216", sk: "Tunisko", en: "Tunisia" },
  { iso: "TR", dial: "+90", sk: "Turecko", en: "Turkey" },
  { iso: "TM", dial: "+993", sk: "Turkménsko", en: "Turkmenistan" },
  { iso: "TV", dial: "+688", sk: "Tuvalu", en: "Tuvalu" },
  { iso: "UG", dial: "+256", sk: "Uganda", en: "Uganda" },
  { iso: "UA", dial: "+380", sk: "Ukrajina", en: "Ukraine" },
  { iso: "AE", dial: "+971", sk: "Spojené arab. emiráty", en: "United Arab Emirates" },
  { iso: "UY", dial: "+598", sk: "Uruguaj", en: "Uruguay" },
  { iso: "UZ", dial: "+998", sk: "Uzbekistan", en: "Uzbekistan" },
  { iso: "VU", dial: "+678", sk: "Vanuatu", en: "Vanuatu" },
  { iso: "VA", dial: "+39", sk: "Vatikán", en: "Vatican City" },
  { iso: "VE", dial: "+58", sk: "Venezuela", en: "Venezuela" },
  { iso: "VN", dial: "+84", sk: "Vietnam", en: "Vietnam" },
  { iso: "YE", dial: "+967", sk: "Jemen", en: "Yemen" },
  { iso: "ZM", dial: "+260", sk: "Zambia", en: "Zambia" },
  { iso: "ZW", dial: "+263", sk: "Zimbabwe", en: "Zimbabwe" },
];
